# mydata.yaml

USER_ID_FIELD: 'user_id'
ITEM_ID_FIELD: 'item_id'
RATING_FIELD: 'rating'
TIME_FIELD: 'timestamp'


train_batch_size: 1024
stopping_step: 100
epochs: 20

gpu_id: '0'
train_neg_sample_args:
  distribution: 'uniform'
  
eval_args:
  split:
    LS: 'valid_and_test'
  group_by: 'user'
  order: 'TO'
  mode: 'uni99'

load_col:
  inter: ['user_id', 'item_id', 'rating', 'timestamp']

MAX_ITEM_LIST_LENGTH: 60


fields:
  user_id: 'token'
  item_id: 'token'
  rating: 'float'
  timestamp: 'float'

eval_batch_size: 4096
eval_step: 1
eval_neg_sample_args:
  neg_sampling: {'uniform': 99} 
  
# 对应模型的具体配置（可以根据使用的模型调整）
# 如果你使用 SASRec 模型
loss_type: 'BPR'
hidden_size: 128
inner_size: 256
n_heads: 1
learning_rate: 0.001

topk: [10]